### ISSUE TITLE
Ability to delete a campaign 

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#181]
- [ ] Add a button under duplicate campaign to delete it. Styling red dashed outline. Red text. Trash icon.
- [ ] A campaign with flights that have served impressions (actuals) cannot be deleted.
- [ ] After its clicked, ensure there's an alert confirming this is actually what the user wants to do.

**Comment by IcusFMagni** [comment]
Decide where the button goes first!

**Comment by brandonhundt** [comment]
The more I think about this, the more I agree with @rickpeterman on this. Lets add a new dropdown button.

To the right of the Save button, in the status bar, lets add a `more_vert` button (three vertical dots): 

`<mat-icon _ngcontent-ffq-c140="" role="img" class="mat-icon notranslate material-icons mat-icon-no-color" aria-hidden="true">more_vert</mat-icon>` 

See: https://material.angular.io/components/button/overview

- If clicked a dropdown appears with extra flight options, like Duplicate and delete campaign. 
- The delete button would be red below a `hr`
- Ensure there's a confirmation when delete is added.

Hopefully this provides enough to go off of. If you want a mockup, let me know.

**Comment by sandikbarr** [comment]
Implementation notes:
* Delete campaign will be implemented with a set of three [NgRx actions](https://v7.ngrx.io/guide/store/actions), CAMPAIGN_DELETE to initiate campaign deletion, and CAMPAIGN_DELETE_SUCCESS/CAMPAIGN_DELETE_FAILURE. Declare these actions with a campaign id and haldoc payload property in the store/actions.
* The campaign HalDoc will be needed in order to call the [destroy](https://github.com/PRX/styleguide.prx.org/blob/master/projects/ngx-prx-styleguide/src/lib/hal/doc/haldoc.ts#L93) method which makes the API delete call. From the Delete button, call a function in campaign-action.service that gets the campaign/campaign HalDoc from state then dispatches the CAMPAIGN_DELETE action. There is an existing NgRx [selector](https://v7.ngrx.io/guide/store/selectors) `selectCampaignDoc` you can subscribe to for this doc.
* [NgRx effects](https://v7.ngrx.io/guide/effects) are used for async operations like API calls. In campaign.effects, add an effect campaignDelete$ that responds to ofType(CAMPAIGN_DELETE)
  * The campaignDelete$ effect will use campaign.service to call destroy on the HalDoc
  * on success, router.navigate back to dashboard with params (as done with dashboard button in status bar)
  * on success, the effect will map to a CAMPAIGN_DELETE_SUCCESS action
  * on API catchError dispatch CAMPAIGN_DELETE_FAILURE
* The campaign and flight [reducers](https://v7.ngrx.io/guide/store/reducers) will respond to campaign delete by resetting to initial state and removing all flight entities

**Comment by brandonhundt** [comment]
After talking with the Ad/ops team, one guardrail to consider is that if a campaign has any actuals, it should not be able to be deleted.

Thanks!
