### ISSUE TITLE
Design for Simulated Baked-in flights

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#189]
Change Uncapped slider to select dropdown.

Options:
- Capped (default)
- Uncapped
- Simulated Baked-in

**Comment by brandonhundt** [comment]
* No Cap toggle update to a select box
* Default value is 'Capped':
![Screen Shot 2020-05-18 at 1.22.37 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/7e62b233-c0c9-48b0-91e3-241fa9d6b27b)

* 2nd value is "Simulated Baked-in", this is a high priority flight that kicks anything else out of the zone.  There is no goal, contract goal, daily min, or delivery options as you get everything.

![Screen Shot 2020-05-18 at 1.27.42 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/31abf98c-5854-4deb-b914-642fc25f0b25)

* 3rd value is "Backup / Remnant", or low priority uncapped flights. Goal and Contract Goal are present, but not required. They can be left empty. If they are filled in the goal field acts as a limiter on the total number of impressions that can be served. "We will take any available impression left over up to the goal without going over".

![Screen Shot 2020-05-18 at 1.32.33 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/d49b0f42-8d1d-4594-9cb9-eca43250899e)

**Comment by cavis** [comment]
When we get around to the frontend implementation for this ... should also restrict/validate the number of zones on "baked in" flights.  You can have companion ads baked-in, but you _cannot_ have multizone non-companion ads, because that doesn't make sense.  (Multizone flights imply only 1 of the 2 zones will end up with the ad in it).
