### ISSUE TITLE
Pause/Cancel flight design

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#206]
Implement the frontend for PRX/augury.prx.org#239.

@brandonhundt may have some thoughts on UI - but I'd suggest just copying the campaign status dropdown.

Note that this field _will_ impact the Flight Preview - setting to "Cancelled" removes all allocations.  The other 2 states allow allocations.

**Comment by brandonhundt** [comment]
Here are my thoughts on Flight Status:

1. I agree with @cavis that the flight state should copy the campaign status and its functionality. 

2. If the flight is in the following: draft, hold, sold, approved, or paused the allocation should be held. If the flight is cancelled the allocations are returned. 

3. The default value for a new flight should be the same as the campaign status. 

4. If the campaign status is changed, all of the flights should be changed, unless a flight has a different status than that of the overall campaign. Basically the campaign status becomes a lever to change all of the individual flight statuses that match that state.

For example: If the campaign status is Approved, all flights should remain approved, unless the state of an individual flight has been changed. Then that flight's status would act independently of the overall campaign status.
 
5. The Flight Status field should appear after the series and before zone selection.

I hope that is helpful. Please let me know if more info or clarification is needed here.

**Comment by brandonhundt** [comment]
After talking with the team, I'm going to put together a flow diagram of the different states and how they interact.

**Comment by brandonhundt** [comment]
![flight_state_flow.jpg](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/780e6c4c-7daa-4264-afa0-16c6eab84afb)

Thoughts for ticket writing (as extrapolated from [this thread](https://prx.slack.com/archives/GCEJE5136/p1595430881003400)):

1. We don't need campaign status field. eventually we might want to consider a frontend thing that updates the status for multiple flights but initially this should live on the frontend.
2. We should discuss pausing a little more in depth and what that looks like from an implementation standpoint.

Otherwise, I think we are able to write implementation tickets on this.
