### ISSUE TITLE
companion toggle

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#211]
add support to set the companion toggle on zone

**Comment by cavis** [comment]
Note: the flights API boolean key is `isCompanion` ... and should work through the preview endpoint as well.

**Comment by brandonhundt** [comment]
Here is an overview of the design aspect of adding a companion: 

Sketch file: https://www.sketch.com/s/add11476-b42d-44cc-a705-8d2bde1f3f69/a/L81O73

![Screen Shot 2020-06-09 at 1.44.42 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/33b3b959-c3a4-492b-93e1-a49fb89fc1eb)

The 'Add a companion' link appears next to 'Add a creative'. If you add a companion, the 'Add a creative' link should not appear. Also if you 'Add a creative' the 'add a companion' link should not appear. 

When you click Add a companion, the user should see another row to select a zone and the creative and eventually add ping backs.

**Comment by cavis** [comment]
Hrmm... that's a _bit_ off from current functionality @brandonhundt.  A flight with > 1 zone is either:

A) "Multi-zone", where it flights in _one_ of your zones but never > 1
  - Ad-ops has actually already been using this feature, as they do a ton of flights that are in "pre_1 OR pre_2" but they don't actually care which.  Both zones have the same mp3/pingbacks/etc.
  - We sort of accidentally introduced this feature awhile back, and it turned out to be useful to ad-ops, so we kept it.

B) "Companion ads", where it has to flight in _all_ of your zones at once or not at all.

Currently (A) is what happens in Grove when you add > 1 zones.  We just need a boolean to explicitly change to (B).

**Comment by sandikbarr** [comment]
Implement as slide toggle
